export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  USER_SIGN_IN_START: "user/USER_SIGN_IN_START",
  USER_SIGN_IN_SUCCESS: "user/USER_SIGN_IN_SUCCESS",
  USER_SIGN_IN_FAILED: "user/USER_SIGN_IN_FAILED",
};
